# Generated by Django 4.2.4 on 2023-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='email',
            field=models.EmailField(max_length=30),
        ),
    ]
