# Generated by Django 4.2.4 on 2023-11-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_onetimecode_counter_alter_onetimecode_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('approach', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='OneTimeCode',
        ),
    ]
