# Generated by Django 4.2.4 on 2023-11-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_reguser_delete_onetimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
